<a href="https://colab.research.google.com/github/DmitriyDikunov/python-4-7/blob/main/Lab1_Dikunov_4_7.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#Завдання 1  8. Створіть одновимірний масив (вектор) зі спадаючою послідовністю чисел, де кожне наступне число менше попереднього на 2, починаючи з 30, та виведіть його значення.
list = []
for i in range(0,31,2):
    list.append(i)
list = list [::-1]
print(list)

[30, 28, 26, 24, 22, 20, 18, 16, 14, 12, 10, 8, 6, 4, 2, 0]


In [ ]:
#Завдання 2 8. Створіть двовимірний масив (матрицю) розміром 3x3, заповніть його значеннями факторіалів натуральних чисел, починаючи з 1, та виведіть його значення
import numpy as np
from math import factorial
matrix = np.zeros((3, 3), dtype=int)
num = 1
for i in range(3):
    for j in range(3):
        matrix[i][j] = factorial(num)
        num += 1
print(matrix)

[[     1      2      6]
 [    24    120    720]
 [  5040  40320 362880]]


In [ ]:
#Завдання 3 8. Створіть масив розміром 4x4, заповніть його випадковими цілими числами від 1 до 10 та виведіть його значення
import random
list = []
for i in range(4):
    row = []
    for j in range(4):
       row.append(random.randint(1, 10))
    list.append(row)
print(list)

[[8, 1, 2, 4], [3, 4, 1, 1], [8, 4, 7, 3], [3, 2, 8, 4]]


In [ ]:
#Завдання 4 8. Створіть масив розміром 6x6, заповніть його випадковими дійсними числами в діапазоні від 0 до 1 та обчисліть суму всіх діагональних елементів
import numpy as np
array = np.random.rand(6, 6)
array = np.round(array, 1)
diagonal_sum = np.trace(array)
print(array, diagonal_sum, sep ='\n')

[[0.8 0.6 0.9 0.4 0.2 0.6]
 [0.1 0.3 0.2 0.9 0.6 0.8]
 [0.2 0.3 0.2 0.9 0.4 0.3]
 [0.5 0.2 1.  0.5 0.5 1. ]
 [0.7 0.1 0.8 0.9 0.5 0.7]
 [0.4 0.1 0.1 0.3 0.7 0.4]]
2.6999999999999997


In [6]:
#Завдання 5 8. Створіть два одновимірних масиви розміром 4, заповніть їх випадковими дійсними числами від -10 до 10 та виконайте на них поелементні операції додавання, віднімання та множення.
import random
list_1 = []
list_2 = []
sum_list = []
minus_list = []
mult_list = []
for i in range(4):
    list_1.append(random.randint(-10,10))
    list_2.append(random.randint(-10, 10))
for i in range(len(list_1)):
    sum_list.append(list_1[i] + list_2[i])
for i in range(len(list_1)):
    minus_list.append(list_1[i] - list_2[i])
for i in range(len(list_1)):
    mult_list.append(list_1[i] * list_2[i])
print(f'Сума = {sum_list}',f'Віднімання = {minus_list}',f'Множення = {mult_list}', sep='\n')

Сума = [-5, 10, 8, -10]
Віднімання = [1, 4, 4, 4]
Множення = [6, 21, 12, 21]


In [5]:
#Завдання 6 8. Створіть дві матриці 4x4, заповніть їх довільними цілими числами від 1 до 5 та знайдіть їх добуток
import numpy as np
matrix_1 = np.random.randint(1, 6, (4, 4))
matrix_2 = np.random.randint(1, 6, (4, 4))
result_matrix = np.dot(matrix_1, matrix_2)
print(matrix_1)
print(matrix_2)
print("Результат множення матриць",result_matrix, sep='\n')

[[1 5 2 1]
 [2 1 2 3]
 [3 4 1 2]
 [5 2 4 5]]
[[2 5 2 5]
 [3 4 1 1]
 [1 2 1 2]
 [5 2 1 2]]
Результат множення матриць
[[24 31 10 16]
 [24 24 10 21]
 [29 37 13 25]
 [45 51 21 45]]


In [7]:
#Завдання 7 8. Створіть дві матриці розміром 2x3 та 3x3, заповніть їх випадковими цілими числами в діапазоні від 1 до 4 та перемножте їх між собою
import numpy as np
matrix_1 = np.random.randint(1, 5, (2, 3))
matrix_2 = np.random.randint(1, 5, (3, 3))
result_matrix = np.dot(matrix_1, matrix_2)
print("Матриця 1:",matrix_1, sep='\n')
print("Матриця 2 ",matrix_2, sep='\n')
print("Результат множення матриць",result_matrix, sep='\n')

Матриця 1:
[[1 1 4]
 [4 4 3]]
Матриця 2 
[[2 2 4]
 [2 3 4]
 [3 1 3]]
Результат множення матриць
[[16  9 20]
 [25 23 41]]


In [ ]:
#Завдання 8 8. Створіть матрицю розміром 3x3, заповніть її випадковими цілими числами в діапазоні від 1 до 7 та знайдіть її обернену матрицю
import numpy as np
matrix = np.random.randint(1, 8, (3, 3))
det = np.linalg.det(matrix)
if det != 0:
    inverse_matrix = np.linalg.inv(matrix)
    print("Оригінальна матриця")
    print(matrix)
    print("\nОбернена матриця:")
    print(inverse_matrix)
else:
    print("Матриця не має оберненої")


Оригінальна матриця
[[4 5 3]
 [7 4 7]
 [3 6 2]]

Обернена матриця:
[[ 3.09090909 -0.72727273 -2.09090909]
 [-0.63636364  0.09090909  0.63636364]
 [-2.72727273  0.81818182  1.72727273]]


In [3]:
#Завдання 9 8.Створіть матрицю розміром 5x5, заповніть її випадковими дійсними числами в діапазоні від -5 до 5 та транспонуйте її.
import numpy as np
matrix = np.random.uniform(-5, 5, (5, 5))
transposed_matrix = np.transpose(matrix)
print("Оригінальна матриця", matrix, sep = '\n')
print("Транспонована", transposed_matrix, sep = '\n')

Оригінальна матриця
[[ 0.53201951 -3.36873724 -0.3086723  -4.26746478 -4.33752535]
 [ 1.56841644  3.22661873  4.58333649 -3.48917305  1.72184285]
 [ 1.60178436 -4.52581107  4.70124688  0.06480278  2.41036974]
 [-3.98858279 -2.46741826 -1.63438875 -1.60878532 -4.88135841]
 [-0.03488552  4.47321772  1.3864401   1.29395369  3.98041218]]
Транспонована
[[ 0.53201951  1.56841644  1.60178436 -3.98858279 -0.03488552]
 [-3.36873724  3.22661873 -4.52581107 -2.46741826  4.47321772]
 [-0.3086723   4.58333649  4.70124688 -1.63438875  1.3864401 ]
 [-4.26746478 -3.48917305  0.06480278 -1.60878532  1.29395369]
 [-4.33752535  1.72184285  2.41036974 -4.88135841  3.98041218]]


In [4]:
#Завдання 10 Створіть матрицю розміром 3x4 та вектор розміром 4x1, заповніть матрицю випадковими цілими числами в діапазоні від 1 до 10, а вектор - випадковими дійсними
#числами від 0 до 1 і знайдіть добуток матриці на вектор.
import numpy as np
matrix = np.random.randint(1, 11, (3, 4))
vector = np.random.uniform(0, 1, (4, 1))
result = np.dot(matrix, vector)
print("3x4", matrix, sep = '\n')
print("4x1",vector, sep = '\n')
print("Результат",result, sep = '\n')

3x4
[[ 2  7  9  7]
 [ 1  2 10  4]
 [ 9  3 10  6]]
4x1
[[0.4549909 ]
 [0.0510683 ]
 [0.00651573]
 [0.93562601]]
Результат
[[7.87548352]
 [4.36478885]
 [9.92703634]]


In [8]:
#Завдання 11 Створіть матрицю розміром 2x3 та вектор розміром 3x1, заповніть матрицю випадковими дійсними числами від 0 до 1, а вектор - випадковими дійсними числами
#від 0 до 1, і знайдіть добуток матриці на вектор
import numpy as np
matrix = np.random.uniform(0, 1, (2, 3))
vector = np.random.uniform(0, 1, (3, 1))
result = np.dot(matrix, vector)
print(matrix)
print(vector)
print(result)

[[0.58212448 0.24197328 0.3481806 ]
 [0.36555294 0.00315941 0.92698781]]
[[0.51043071]
 [0.40763307]
 [0.78001779]]
[[0.66735758]
 [0.9109443 ]]


In [9]:
#Завдання 12 Створіть дві матриці розміром 9x9, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та знайдіть відношення елементів другої матриці до першої
#(поелементне ділення)
import numpy as np
matrix_1 = np.random.randint(1, 11, (9, 9))
matrix_2 = np.random.randint(1, 11, (9, 9))
result = matrix_2 / matrix_1
print(matrix_1)
print(matrix_2)
print(result)


[[ 5  4  1  5  9  1  9  4  1]
 [ 7  4  9  1  9  9  1  7  6]
 [10  4  1  6  8  7  2  9  8]
 [ 5  2  7  1 10  1  8 10 10]
 [ 3  7  4  9  6 10  5  6  4]
 [ 8  2  2  3  8  6  4  3  9]
 [ 2  5  2  9  7  6  8  6  4]
 [ 8  6  6  5 10  3  7  7  8]
 [ 1  5  4  5  8  2  4  9  6]]
[[ 7 10  1  8  5  5  8  2  6]
 [ 9  9  3  5  6  8  9  4 10]
 [ 7  8  9  1  8  2  5  1  4]
 [10  9  6  1 10  2  4  1  5]
 [ 2 10 10  4 10  4  8  4  1]
 [ 9  1  8  4  3  3  8  2  9]
 [10  2  4  6 10  9  3  1  4]
 [ 1  9  8  6  7  2  1  7  9]
 [ 9 10  7  6  9  9  7  3  1]]
[[1.4        2.5        1.         1.6        0.55555556 5.
  0.88888889 0.5        6.        ]
 [1.28571429 2.25       0.33333333 5.         0.66666667 0.88888889
  9.         0.57142857 1.66666667]
 [0.7        2.         9.         0.16666667 1.         0.28571429
  2.5        0.11111111 0.5       ]
 [2.         4.5        0.85714286 1.         1.         2.
  0.5        0.1        0.5       ]
 [0.66666667 1.42857143 2.5        0.44444444 1.66666667 0

In [10]:
#Завдання 13 Створіть дві матриці розміром 9x9, заповніть їх випадковими цілими числами в діапазоні від 1 до 5 та знайдіть їх добуток
import numpy as np
matrix_1 = np.random.randint(1, 6, (9, 9))
matrix_2 = np.random.randint(1, 6, (9, 9))
result = np.dot(matrix_1, matrix_2)
print(matrix_1)
print(matrix_2)
print(result)

[[3 3 3 4 4 2 4 4 5]
 [1 2 5 5 3 2 1 4 5]
 [3 5 3 1 5 2 4 5 1]
 [4 5 5 5 1 4 2 3 2]
 [4 5 3 1 5 5 4 4 3]
 [1 1 3 4 3 2 4 3 3]
 [2 4 1 2 3 5 4 5 3]
 [1 1 4 1 5 1 1 2 3]
 [1 1 5 3 1 4 4 4 5]]
[[3 2 2 2 5 3 3 1 4]
 [2 1 5 2 2 2 4 1 2]
 [4 3 2 3 5 4 3 2 4]
 [2 4 2 2 1 5 1 3 5]
 [1 3 3 3 5 5 5 5 2]
 [2 2 5 4 2 3 1 3 3]
 [3 1 1 1 2 5 3 4 2]
 [1 4 4 2 5 2 3 3 4]
 [3 1 2 4 4 2 5 2 3]]
[[ 74  75  87  81 112 111 105  88 103]
 [ 66  74  78  77 100  96  88  75  98]
 [ 62  68  90  68 107  99  98  81  86]
 [ 76  75  94  78 100 104  86  72 107]
 [ 76  74 107  88 121 113 111  92 101]
 [ 56  60  62  60  80  90  73  72  79]
 [ 61  65  94  74  95  94  89  81  88]
 [ 44  48  52  54  79  69  70  57  59]
 [ 71  66  76  76  96  95  83  76  94]]


In [11]:
#Завдання 14 Створіть матрицю розміром 3x3, заповніть її випадковими цілими числами в діапазоні від -5 до 5 та знайдіть середнє арифметичне значення елементів матриці
import numpy as np
matrix = np.random.randint(-5, 6, (3, 3))
mean_value = np.mean(matrix)
print(matrix)
print(mean_value)


[[ 4 -4 -2]
 [ 0 -4  1]
 [ 4 -4 -3]]
-0.8888888888888888


In [12]:
#Завдання 15 Створіть матрицю розміром 10x10, заповніть її випадковими дійсними числами в діапазоні від -2 до 2 та знайдіть вектор-стовпчик, що містить найменше за модулем
#значення елементу у кожному рядку матриці.
import numpy as np
matrix = np.random.uniform(-2, 2, (10, 10))
min_abs_values = np.min(np.abs(matrix), axis=1)
print(matrix)
print(min_abs_values)


[[ 1.13228893  1.08135336  0.08620744  1.96810447 -1.54588425  0.94921724
  -0.4511118   0.05894896  0.28168109 -0.97079411]
 [-1.4320512  -0.83306038 -0.50852635  1.31613894 -0.57767238  0.35922936
   1.46614245  1.30564375  1.84129186  1.35889242]
 [-1.05912296 -0.40493505  0.48706389 -1.62362366 -0.32536418 -0.78966721
  -0.17567849  0.25277948 -1.09694268 -1.08526387]
 [ 0.33636743 -0.06197914 -1.34075026  1.17145945  0.2425957   1.94498675
   1.72654691  1.57670783  0.37108106 -0.14408598]
 [-1.18307167  0.84115997 -0.1008513  -1.87891163  0.63153997 -1.58915611
  -1.65317695 -0.16569783  1.23397937  0.25635788]
 [-0.68818845 -0.92644238 -0.69877923 -1.58490607  0.6144456   0.67763339
   1.5284746  -1.46811494  0.3322089   1.17513371]
 [-0.51916932  0.77717837 -0.48433138  0.84947702  0.63189775  1.76429135
   0.84658721  1.98260852 -1.18874271  1.90789645]
 [-0.30256337 -0.01244837 -0.62663009 -0.46862108  0.58983638 -1.66090721
  -1.95814267 -0.58531273  0.82056503 -1.4530308 ]
